"""Add cascade delete for cache foreign keys

Revision ID: 534a3ad52962
Revises: 17a05c5a0377
Create Date: 2025-12-22 02:52:58.349323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '534a3ad52962'
down_revision = '17a05c5a0377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints
    op.drop_constraint('wb_product_cache_token_id_fkey', 'wb_product_cache', type_='foreignkey')
    op.drop_constraint('cache_sync_log_token_id_fkey', 'cache_sync_log', type_='foreignkey')
    
    # Add new foreign key constraints with CASCADE DELETE
    op.create_foreign_key(
        'wb_product_cache_token_id_fkey', 
        'wb_product_cache', 
        'wb_token', 
        ['token_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'cache_sync_log_token_id_fkey', 
        'cache_sync_log', 
        'wb_token', 
        ['token_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop CASCADE foreign key constraints
    op.drop_constraint('wb_product_cache_token_id_fkey', 'wb_product_cache', type_='foreignkey')
    op.drop_constraint('cache_sync_log_token_id_fkey', 'cache_sync_log', type_='foreignkey')
    
    # Restore original foreign key constraints without CASCADE
    op.create_foreign_key(
        'wb_product_cache_token_id_fkey', 
        'wb_product_cache', 
        'wb_token', 
        ['token_id'], 
        ['id']
    )
    op.create_foreign_key(
        'cache_sync_log_token_id_fkey', 
        'cache_sync_log', 
        'wb_token', 
        ['token_id'], 
        ['id']
    )
    
    # ### end Alembic commands ###
