"""Add product cache and sync log tables

Revision ID: 7069d166d2bd
Revises: 98c067f0f441
Create Date: 2025-12-19 03:11:20.258420

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7069d166d2bd'
down_revision = '98c067f0f441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_sync_log',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('products_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['wb_token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_sync_log_started_at'), 'cache_sync_log', ['started_at'], unique=False)
    op.create_index(op.f('ix_cache_sync_log_token_id'), 'cache_sync_log', ['token_id'], unique=False)
    op.create_table('wb_product_cache',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('wb_product_id', sa.Integer(), nullable=False),
    sa.Column('product_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('cache_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['wb_token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_product_cache_is_active'), 'wb_product_cache', ['is_active'], unique=False)
    op.create_index(op.f('ix_wb_product_cache_last_updated'), 'wb_product_cache', ['last_updated'], unique=False)
    op.create_index(op.f('ix_wb_product_cache_token_id'), 'wb_product_cache', ['token_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cache_wb_product_id'), 'wb_product_cache', ['wb_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_product_cache_wb_product_id'), table_name='wb_product_cache')
    op.drop_index(op.f('ix_wb_product_cache_token_id'), table_name='wb_product_cache')
    op.drop_index(op.f('ix_wb_product_cache_last_updated'), table_name='wb_product_cache')
    op.drop_index(op.f('ix_wb_product_cache_is_active'), table_name='wb_product_cache')
    op.drop_table('wb_product_cache')
    op.drop_index(op.f('ix_cache_sync_log_token_id'), table_name='cache_sync_log')
    op.drop_index(op.f('ix_cache_sync_log_started_at'), table_name='cache_sync_log')
    op.drop_table('cache_sync_log')
    # ### end Alembic commands ###
