"""Add WBToken table

Revision ID: 98c067f0f441
Revises: 1a31ce608336
Create Date: 2025-12-11 08:12:07.811844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '98c067f0f441'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_token',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trade_mark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_token')
    # ### end Alembic commands ###
