"""add_wb_subject_characteristics_cache_table

Revision ID: a3b11b8bcb83
Revises: 534a3ad52962
Create Date: 2025-12-23 06:28:24.404846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a3b11b8bcb83'
down_revision = '534a3ad52962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_subject_characteristics_cache',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('characteristics_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('cache_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_subject_characteristics_cache_is_active'), 'wb_subject_characteristics_cache', ['is_active'], unique=False)
    op.create_index(op.f('ix_wb_subject_characteristics_cache_last_updated'), 'wb_subject_characteristics_cache', ['last_updated'], unique=False)
    op.create_index(op.f('ix_wb_subject_characteristics_cache_subject_id'), 'wb_subject_characteristics_cache', ['subject_id'], unique=True)
    op.drop_constraint(op.f('cache_sync_log_token_id_fkey'), 'cache_sync_log', type_='foreignkey')
    op.create_foreign_key(None, 'cache_sync_log', 'wb_token', ['token_id'], ['id'])
    op.drop_constraint(op.f('wb_product_cache_token_id_fkey'), 'wb_product_cache', type_='foreignkey')
    op.create_foreign_key(None, 'wb_product_cache', 'wb_token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wb_product_cache', type_='foreignkey')
    op.create_foreign_key(op.f('wb_product_cache_token_id_fkey'), 'wb_product_cache', 'wb_token', ['token_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cache_sync_log', type_='foreignkey')
    op.create_foreign_key(op.f('cache_sync_log_token_id_fkey'), 'cache_sync_log', 'wb_token', ['token_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wb_subject_characteristics_cache_subject_id'), table_name='wb_subject_characteristics_cache')
    op.drop_index(op.f('ix_wb_subject_characteristics_cache_last_updated'), table_name='wb_subject_characteristics_cache')
    op.drop_index(op.f('ix_wb_subject_characteristics_cache_is_active'), table_name='wb_subject_characteristics_cache')
    op.drop_table('wb_subject_characteristics_cache')
    # ### end Alembic commands ###
